language: python

os:
  - linux

python:
  - "3.8"

cache: pip

install:
  - pip install --upgrade pip
  - pip install --upgrade pipenv
  - pipenv install --verbose

script:
  - pipenv run coverage run --source='.' manage.py test
  - pipenv run coverage report -m --skip-covered

after_success:
  - pipenv run coveralls
install: