language: python

os:
  - linux

python:
  - "3.8"

cache: pip

install:
  - pipenv install -d

script:
  - pipenv run python manage.py test && pipenv run coverage report -m --skip-covered

after_success:
  - pipenv run coveralls
