# Generated by Django 3.0.8 on 2020-08-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20200714_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modified'),
        ),
    ]
